var mn118=[[
 {name:"mn118.p1",content:"Evaṁ me sutaṁ: ekaṁ samayaṁ Bhagavā Sāvatthiyaṁ viharati\nPubbārāme Migāramātupāsāde,\nsambahulehi abhiññātehi abhiññātehi Therehi Sāvakehi saddhiṁ\nāyasmatā ca Sāriputtena, āyasmatā ca Mahāmoggallānena,\nāyasmatā ca Mahākassapena, āyasmatā ca Mahākaccāyanena,\nāyasmatā ca Mahākoṭṭhitena, āyasmatā ca Mahākappinena,\nāyasmatā ca Mahācundena, āyasmatā ca Anuruddhena, \nāyasmatā ca Revatena, āyasmatā ca Ānandena,\naññehi ca abhiññātehi abhiññātehi Therehi Sāvakehi saddhiṁ.\n"}
,{name:"mn118.p2",content:"Tena kho pana samayena Therā bhikkhū nave bhikkhū  ovadanti anusāsanti.\nAppekacce Therā bhikkhū dasa pi bhikkhū ovadanti anusāsanti,\nappekacce Therā bhikkhū vīsam-pi  bhikkhū ovadanti anusāsanti,\nappekacce Therā bhikkhū tiṁsam-pi bhikkhū ovadanti anusāsanti,\nappekacce Therā bhikkhū cattārīsam-pi  bhikkhū ovadanti anusāsanti,\nte ca navā bhikkhū Therehi bhikkhūhi ovadiyamānā anusāsiyamānā\nuḷāraṁ  pubbenāparaṁ visesaṁ pajānanti. \nTena kho pana samayena Bhagavā Tad-ahuposathe pannarase,  \nPavāraṇāya puṇṇāya puṇṇamāya rattiyā, \nBhikkhusaṅghaparivuto abbhokāse nisinno hoti."} 
,{name:"mn118.p3",content:"Atha kho Bhagavā, \ntuṇhībhūtaṁ tuṇhībhūtaṁ  Bhikkhusaṅghaṁ anuviloketvā, bhikkhū āmantesi:\n“Āraddhosmi bhikkhave imāya paṭipadāya,\nāraddhacittosmi bhikkhave imāya paṭipadāya\ntasmātiha bhikkhave bhiyyosomattāya viriyaṁ  ārabhatha\nappattassa pattiyā, anadhigatassa adhigamāya, asacchikatassa sacchikiriyāya,\nidhevāhaṁ Sāvatthiyaṁ Komudiṁ cātumāsiniṁ āgamissāmī.” ti "}
,{name:"mn118.p4",content:"Assosuṁ kho jānapadā bhikkhū:\n“Bhagavā kira tattheva Sāvatthiyaṁ Komudiṁ cātumāsiniṁ āgamissatī,” ti\nte ca  jānapadā bhikkhū Sāvatthiṁ  osaranti Bhagavantaṁ dassanāya. \nTe ca kho  Therā bhikkhū bhiyyosomattāya nave bhikkhū ovadanti anusāsanti,\nappekacce Therā bhikkhū dasa pi bhikkhū ovadanti anusāsanti,\nappekacce Therā bhikkhū visam-pi bhikkhū ovadanti anusāsanti,\nappekacce Therā bhikkhū tiṁsam-pi bhikkhū ovadanti anusāsanti,\nappekacce Therā bhikkhū cattārīsam-pi bhikkhū ovadanti anusāsanti,\nte ca navā bhikkhū therehi bhikkhūhi ovadiyamānā anusāsiyamānā\nuḷāraṁ pubbenāparaṁ visesaṁ pajānanti.\nTena kho pana samayena Bhagavā Tad-ahuposathe pannarase,\nKomudiyā cātumāsiniyā puṇṇāya puṇṇamāya rattiyā, \nBhikkhusaṅghaparivuto abbhokāse nisinno hoti."}
],
[
 {name:"mn118.p1.e",content:"Thus I heard: at one time the Gracious One was dwelling near Sāvatthī\nat Migāra's Mother's mansion in the Eastern Grounds,\ntogether with a great many very well-known Elder Disciples\n(such as) with venerable Sāriputta, with venerable Mahāmoggallāna,\nwith venerable Mahākassapa, with venerable Mahākaccāyana,\nwith venerable Mahākoṭṭhita, with venerable Mahākappina,\nwith venerable Mahācunda, with venerable Anuruddha,\nwith venerable Revata, with venerable Ānanda,\ntogether with other very well-known Elder Disciples."}
,{name:"mn118.p2.e",content:"Then at that time the Elder monks were advising and instructing the new monks. \nSome Elder monks were advising and instructing ten monks,\nsome Elder monks were advising and instructing twenty monks,\nsome Elder monks were advising and instructing thirty monks,\nsome Elder monks were advising and instructing forty monks,\nand while those new monks were being advised and instructed by the Elder monks\nthey came to know successive lofty attainments. \nThen at that time the Gracious One, on that very Uposatha day of the fifteenth, \non the Pavāraṇā full moon night, \nwas sat in the open air surrounded by the Community of monks.\n"}
,{name:"mn118.p3.e",content:"Then the Gracious One,\n after seeing the community of monks were maintaining complete silence, addressed the monks (saying):\n“I am satisfied,  monks, with this practice,\nmy mind is satisfied with this practice,\ntherefore, monks, put forth even more energy\nfor the attainment of the unattained, for the accomplishment of the unaccomplished, for the realisation of the unrealised, \nI will be right here at Sāvatthī until the fourth month of Komudī comes.” "}
,{name:"mn118.p4.e",content:"The monks in the country heard:\n“The Gracious One will be right there at Sāvatthī until the fourth month of Komudī comes,”\nand those monks in the country descended on Sāvatthī to see the Gracious One.\nThose Elder monks put forth even more energy advising and instructing the new monks,\nsome Elder monks were advising and instructing ten monks,\nsome Elder monks were advising and instructing twenty monks,\nsome Elder monks were advising and instructing thirty monks,\nsome Elder monks were advising and instructing forty monks,\nand while those new monks were being advised and instructed by the Elder monks\nthey came to know (even more) successive lofty attainments.\nThen at that time the Gracious One, on that very Uposatha day of the fifteenth,\non the Komudī full moon night at the end of four months,\nwas sat in the open air surrounded by the Community of monks."}
]

];
module.exports=mn118;