var yijing=[[
        {name:"qian",cols:3,content:"乾\n元亨，利貞。天行健，君子以自強不息。\n初九：潛龍，勿用。\n九二：見龍在田，利見大人。\n九三：君子終日乾乾，夕惕若，厲，无咎。\n九四：或躍在淵，无咎。\n九五：飛龍在天，利見大人。\n上九：亢龍有悔。\n用九：見群龍无首，吉。"}
        ,{name:"kun",content:"坤\n元亨，利牝馬之貞。君子有攸往，先迷後得主，利西南得朋，東北喪朋。安貞，吉。\n地勢坤，君子以厚德載物。\n初六：履霜，堅冰至。\n六二：直，方，大，不習无不利。\n六三：含章可貞。或從王事，无成有終。\n六四：括囊；无咎，无譽。\n六五：黃裳，元吉。\n上六：龍戰于野，其血玄黃。\n用六：利永貞。"}
]
        /*
        ,{name:"v3",content:"屯\n元亨，利貞，勿用有攸往，利建侯。屯，剛柔始交而難生，動乎險中，大亨貞。雷雨之動滿盈，天造草昧，宜建侯而不寧。\n初九：磐桓；利居貞，利建侯。六二：屯如邅如，乘馬班如。匪寇婚媾，女子貞不字，十年乃字。六三：即鹿无虞，惟入于林中，君子幾不如舍，往吝。六四：乘馬班如，求婚媾，往吉，无不利。九五：屯其膏，小貞吉，大貞凶。上六：乘馬班如，泣血漣如。"}
        ,{name:"v4",content:"蒙\n亨。匪我求童蒙，童蒙求我。初筮告，再三瀆，瀆則不告。利貞。\n蒙，山下有險，險而止，蒙。蒙亨，以亨行時中也。匪我求童蒙，童蒙求我，志應也。初噬告，以剛中也。再三瀆，瀆則不告，瀆蒙也。蒙以養正，聖功也。\n初六：發蒙，利用刑人，用說桎梏，以往吝。九二：包蒙吉；納婦吉；子克家。六三：用取女；見金夫，不有躬，无攸利。六四：困蒙，吝。六五：童蒙，吉。上九：擊蒙；不利為寇，利禦寇。"}*/
,[{name:"qian.e1",cols:9,content:"Qian (represents) what is great and originating, penetrating, advantageous, correct and firm.\nHeaven, in its motion, (gives the idea of) strength. The superior man, in accordance with this, nerves himself to ceaseless activity.\nIn the first (or lowest) NINE, undivided, (we see its subject as) the dragon lying hid (in the deep). It is not the time for active doing.In the second NINE, undivided, (we see its subject as) the dragon appearing in the field. It will be advantageous to meet with the great man.\nIn the third NINE, undivided, (we see its subject as) the superior man active and vigilant all the day, and in the evening still careful and apprehensive. (The position is) dangerous, but there will be no mistake.\nIn the fourth NINE, undivided, (we see its subject as the dragon looking) as if he were leaping up, but still in the deep. There will be no mistake.\nIn the fifth NINE, undivided, (we see its subject as) the dragon on the wing in the sky. It will be advantageous to meet with the great man.\nIn the sixth (or topmost) NINE, undivided, (we see its subject as) the dragon exceeding the proper limits. There will be occasion for repentance.\n(The lines of this hexagram are all strong and undivided, as appears from) the use of the number NINE. If the host of dragons (thus) appearing were to divest themselves of their heads, there would be good fortune."}
 ,{name:"kun.e1",content:"Kun (represents) what is great and originating, penetrating, advantageous, correct and having the firmness of a mare. When the superior man (here intended) has to make any movement, if he take the initiative, he will go astray; if he follow, he will find his (proper) lord. The advantageousness will be seen in his getting friends in the south-west, and losing friends in the north-east. If he rest in correctness and firmness, there will be good fortune.\nThe (capacity and sustaining) power of the earth is what is denoted by Kun. The superior man, in accordance with this, with his large virtue supports (men and) things.\nIn the first SIX, divided, (we see its subject) treading on hoarfrost. The strong ice will come (by and by).\nThe second SIX, divided, (shows the attribute of) being straight, square, and great. (Its operation), without repeated efforts, will be in every respect advantageous.\nThe third SIX, divided, (shows its subject) keeping his excellence under restraint, but firmly maintaining it. If he should have occasion to engage in the king's service, though he will not claim the success (for himself), he will bring affairs to a good issue.\nThe fourth SIX, divided, (shows the symbol of) a sack tied up. There will be no ground for blame or for praise.\nThe fifth SIX, divided, (shows) the yellow lower garment. There will be great good fortune.\nThe sixth SIX, divided (shows) dragons fighting in the wild. Their blood is purple and yellow.\n(The lines of this hexagram are all weak and divided, as appears from) the use of the number six. If those (who are thus represented) be perpetually correct and firm, advantage will arise."}
]];
module.exports=yijing;